---
# tasks file for beats

- name: Set beats_products (legacy)
  set_fact:
    beats_products: "{{ products }}"
  when: products is defined

- name: Set beats_version (legacy)
  set_fact:
    beats_version: "{{ beats_ver }}"
  when: beats_ver is defined

- include: deps.yml

- include_tasks: install.yml
  with_items: "{{ beats_products }}"
