---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-beats
      beats_version: 6.7.2
      beats_hold_products: true
      beats_products:
        - filebeat
        - metricbeat
      filebeat_config:
        filebeat.modules:
          - module: system
            syslog:
              enabled: true
        output.logstash.hosts:
          - logstash.server:5044
      metricbeat_config:
        metricbeat.modules:
          - module: system
            metricsets: ["cpu", "memory", "network"]
            enabled: true
            period: 15s
            processes: ['.*']
        output.logstash.hosts:
          - logstash.server:5044
